### ISSUE TITLE
GetMouseX undefined

### ISSUE THREAD

**Issue by Radnen** [spheredev/neosphere#10]
Here is a test of a a pathfinding demo: https://www.dropbox.com/s/o6t110uoiehv686/PathingTest.zip?dl=0

I get the error:

> identifier 'GetMouseX' undefined

**Comment by fatcerberus** [comment]
Okay, these are odd.  I know for a fact GetMouseX() exists because the SSFML mouse test works.  What sorcery are these games doing to confuse it?

**Comment by fatcerberus** [comment]
Okay, yeah, this pathfinding thing runs on my end with no errors (note that it doesn't work properly, however: mouse clicks are not registered--I will have to investigate).  You must be using an older build of minisphere.

Edit: Turns out the mouse clicks were registered just fine, I just wasn't honoring the initial fill color for CreateSurface.  Having done that fix, the pathfinding demo now runs perfectly.  Closing this as "invalid" since there's no "works for me" tag.

**Comment by Radnen** [comment]
You are correct, I accidentally used an older build when I switched between SSFML and the wrong minisphere, oops.
