### ISSUE TITLE
GetSystemUpArrow

### ISSUE THREAD

**Issue by Radnen** [spheredev/neosphere#11]
Version: 1.03b

> GetSystemUpArrow(): no system up arrow image available.

``` javascript
var img = GetSystemUpArrow();
```

**Comment by fatcerberus** [comment]
This means your system directory doesn't contain a system.ini specifying a valid up-arrow image.  I opted to have these fail-on-call in that case (since they're not often used, you can leave them out if your game doesn't need them) instead of what Sphere would do (I think...) and fail immediately on startup.

**Comment by fatcerberus** [comment]
Okay, nevermind, it was clearly a brainfart on my part:

```
if (s_sys_up_arrow != NULL)
    duk_error(ctx, DUK_ERR_ERROR, "GetSystemUpArrow(): No system up arrow image available");
```

It's now fixed.
