### ISSUE TITLE
FlipScreen hangs when frame limiting disabled after frameskip

### ISSUE THREAD

**Issue by Radnen** [spheredev/neosphere#14]
Version: minisphere 1.0

I tried one of my simplest games, a game for Ludum Dare 31 where all you do is basically interview people. After talking to anyone once, the game locks up. I don't get access to input or anything.

Game: [LD31: Whodunnit](https://www.dropbox.com/s/mii88287vs0ts1i/LD31.zip?dl=0)

**Comment by fatcerberus** [comment]
Just to make sure: this is minisphere 1.0, yes? ;-)

I'm not near a computer at present, but I will check it out later on.  I know I experienced a few lockups myself with Trial and Error that I couldn't resolve.  For what it's worth I don't think it's minisphere--I suspect a deadlock in either Allegro or Duktape.

**Comment by Radnen** [comment]
It's minisphere 1.0. For the record, it doesn't work in SSFML either, but it has more to do with the way key input is handled, but at least it doesn't pause the game indefinitely.

The key queue is... odd in Sphere since input isn't like that for every library out there. I'm emulating a key queue, but the downside is some things are queued and others aren't. Map-based key presses (movement, talk key, etc.) don't go in the key queue, but other key presses do. So it's strange for me to try and differentiate that since IMO input is input.

**Comment by fatcerberus** [comment]
Let's see if we can rule out some stuff.  Run engine.exe with this command line: 
--frameskip 0 --no-throttle

Tell me if the lockup still happens.

**Comment by Radnen** [comment]
Ok, I diagonsed it. It's an input thing. Hitting SPACEBAR to leave the talk menu promptly brings it back up since it is also the ON_TALK key. With your frameskip options enabled I can see this, without the options it hangs up.

I think you have the same problem I'm having with SSFML?

**Comment by fatcerberus** [comment]
Odd, so passing `--frameskip 0` (which _disables_ frameskip; the default frameskip is 5) on the command line makes it not lock up?  That's interesting.

You're not by any chance handling input in a render script or something are you?  minisphere's frameskip algorithm is very aggressive and the render script won't be run if the frame is skipped (the update script will, of course).

Out of curiosity, does this game use BindKey at all?

**Comment by fatcerberus** [comment]
My first real bug!  I love a good challenge! :smile:

But yeah, I reproduced the bug.  This is different than the Trial & Error hangs I was experiencing, which were hard deadlocks and required Task Manager to get out of.  In this case I could still close the window, which means the engine is still responding to events.  That narrows things down: Something's getting caught in an infinite loop somewhere.

So I ran it in the debugger (I'm so glad I implemented that Open Game dialog!), and found something interesting: It's apparently getting stuck in an infinite loop waiting for the next frame.  And it's truly infinite: VS says the value of `s_next_frame_time` is `1.#INF000000000000` -- infinity.

Considering that `--frameskip 0` made the issue go away, apparently my frame skipping logic is bugged somewhere.

**Comment by fatcerberus** [comment]
I figured it out, it's a divide-by-zero bug.  Take a look at these two lines:

```
if (!is_backbuffer_valid && !s_skipping_frame)  // did we just finish skipping frames?
    s_next_frame_time = al_get_time() + 1.0 / framerate;
```

`is_backbuffer_valid` is false if the previous frame was skipped; this is used to reset the timing after a frameskip to prevent a long string of updates while the engine tries to catch up, as generally happens in Sphere when the engine gets too bogged down.

Here's what happened: The map engine is running at 60fps; however, because SetFrameRate wasn't called, FlipScreen is unthrottled--and `framerate` is thus 0 during the menu loop.  After the first textbox closes, the engine skips frames trying to catch up (as it was a blocking operation).  Then a menu immediately opens up again.  The engine sees that the last frame was skipped and tries to reset the timer, but because `framerate` is now zero, `s_next_frame_time` is calculated as infinity and, well... there's your lockup. :-)

**Comment by fatcerberus** [comment]
The fix for this is now in master.
