### ISSUE TITLE
IT music loops even when I tell it not to

### ISSUE THREAD

**Issue by DaVince** [spheredev/neosphere#17]
OGG sounds work fine, but IT modules keep looping even if I use .play(false). See this example:

http://davince.tengudev.com/sphere/minisphere-tests/test04%20(looping%20it%20music).zip

**Comment by fatcerberus** [comment]
Hm, interesting: While the IT music incorrectly loops in minisphere, it _doesn't play at all_ in Sphere.  Of course, this is true even if I set the loop flag to true, so maybe Sphere just doesn't like the file...

**Comment by DaVince** [comment]
A bug was introduced in 1.5 that basically broke IT music playback. It works in older versions. That was also the reason I switched to OGG files for music at the time.

**Comment by fatcerberus** [comment]
Ah, good to know.  I hadn't realized, since the music in Steps of the Blackfoot plays in 1.5.  See, isn't it a good thing minisphere is a thing now?  All those long-standing bugs in the vanilla engine get fixed and you don't have to jump through a hundred hoops to compile it!  And it's faster to boot... :)

I'll see what I can do about the erroneous looping.  Probably a flag I have to set on the stream in Allegro.

**Comment by fatcerberus** [comment]
Best I can tell this is a bug in Allegro.  I've reported it on the Allegro forums, so let's see what happens. :-)

**Comment by fatcerberus** [comment]
Good news: The bug report was responded to and it looks like it might get a fix soon.  Unfortunately, I may have to put this fix off for another release regardless.  I just upgraded to the latest Allegro release, and now I'm getting random deadlocks when playing WAV sounds.  Not good.

If only I could build Allegro binaries for Windows, I could probably fix these kinds of bugs myself... alas, last time I tried I got compiler errors and couldn't build it.

**Comment by fatcerberus** [comment]
So the good news is I managed to get Allegro building on my computer--I just needed the DirectX SDK and a LOT of free time.  The bad news is that the modification I tried to do to fix it causes Allegro to overrun its stream buffer and crash the engine for some strange reason.

Does this .it file have looping information stored in it?  DUMB, the module library used by Allegro, honors loop points by default and requires one to explicitly terminate the stream with a callback when a loop point is hit, but the segfaults make that unfeasible.  If you can edit the .it yourself to remove the looping information, that would help.  Obviously I do still have to fix this since the behavior differs from Sphere's, but this would be a workaround at least.

**Comment by DaVince** [comment]
The IT modules for this game don't have specific looping points because I knew I needed to convert them to OGG files.

That said, module music is made to loop by default, I think. Any music tracker I've seen loops it, anyway. It's kinda inherent to the format. Also, the way a loop point works is by sending a command at any point that says "now go back to playing this earlier pattern" so I'm not sure the concept of looping points is even the same to other formats.

**Comment by fatcerberus** [comment]
Yeah, the long and short of it is that, to fix it I have to instruct DUMB to stop playing when it hits a loop point (via a callback), which works--but for whatever reason Allegro doesn't like the feed being cut off like that and ends up writing past the end of the stream buffer, corrupting the heap and segfaulting.

Now that I can compile Allegro myself, I will have to see if I can debug the buffer overrun and then I can close the book on this bug for good. :-)

**Comment by fatcerberus** [comment]
Well, they pulled through! The Allegro devs fixed both issues--the erroneous looping _and_ the buffer overflow.  Try the latest master: It should be fixed now. :-D

**Comment by fatcerberus** [comment]
Damn, I just realized this issue won't actually be fixed for you on Linux, since you'd be building against stock Allegro libs.  I assure you it's fixed in the Windows build of minisphere though! :-P
