### ISSUE TITLE
Make FollowPerson() trailing algorithm more realistic

### ISSUE THREAD

**Issue by DaVince** [spheredev/neosphere#22]
When enabling FollowPerson(), what happens is that the follower will stay in place for the duration of [amount of pixels you defined for the follow distance]. After that it will _immediately_ change its position to [leader position]. This feels unnatural, especially when the follower is somewhat far away, and it makes the function pretty pointless. Frankly, I've always considered it a bug in the original engine.

So I suggest that the follower should first take this time to get to whatever the leader's last position was [follow distance] frames earlier. This would happen at a maximum speed that is at most 3 or 4 times the leader's regular speed, so it looks like the follower is really catching up. And when the follower has arrived at this position, _then_ activate the regular trailing behavior.

**Comment by fatcerberus** [comment]
This is certainly possible, it requires some changes to the follow algorithm though, specifically an additional "catching up" phase.

The thing here is that you have to ensure the follower catches on at the exact frame the leader's starting position falls off of the step history--not for any technical reason (it's easy enough to maintain the target position separately from the normal step history)--but simply to avoid any rubber-banding effects, which would feel unnatural and put us back at square one.

It helps that Sphere uses floating point for person speeds; that means the proper speed required to catch up can be arrived at with a simple division, no Bresenham-type shenanigans needed.  The tricky part is that you want to cap the catch-up speed at 3-4x; if more speed would be needed to get there within (distance / leader_speed) frames, things become messy, and some form of pathfinding becomes almost a necessity.

**Comment by FlyingJester** [comment]
I would think that a good compromise would be to warp the follower directly to the same X and Y as the leader immediately when FollowPerson is called.
This would avoid the awkward bit before the follower actually starts following, and still be a simple solution.

**Comment by fatcerberus** [comment]
I actually thought that was how it worked already--you mean there's a delay before the following person warps into place?  If so, that's definitely a bug.

**Comment by DaVince** [comment]
I'd avoid warping at all if possible.

> if more speed would be needed to get there within (distance / leader_speed) frames, things become messy, and some form of pathfinding becomes almost a necessity.

I wasn't really thinking of a Bresenham type system but just a simple "if (followery > leadery) go up; if (followery is close to leadery) just set it to that same y" etc type thing, until it's so close that it can just start reading the leader's buffer and position itself there. I imagine this would be more than enough for a simple fix.

**Comment by fatcerberus** [comment]
I think I figured out a way this could work.

The current implementation requires any person with followers to maintain a circular history of their last X positions, where X = distance of farthest follower, with new entries entering at the left and eventually falling off the right end of the buffer.  This means the position of a follower on any given frame can always be found at `leader->steps[distance]`

The problem, of course, is that the engine doesn't know what distance you are going to set and we can't have every single person on a map maintaining a 1K step history in case they eventually get followers attached.  The history buffers are allocated on demand when a follower is attached and zero-initialized--meaning the target position isn't actually known until the leader has moved `distance` steps after the attachment...

**Comment by fatcerberus** [comment]
Just started work on this today.  My planned implementation is: When a follower is attached, the engine doesn't warp that person at all; it stays where it is.  After the leader has taken [distance] steps, the follower begins walking in the direction of their place in the formation at twice the usual speed until they catch up, after which it switches over to the usual caterpillar algorithm (i.e. propagating historical positions along the follower chain).

As for what constitutes being "caught up", I defined it as the follower being within one step of their place in the formation, based on their current speed.  If this is the case, it's then safe for them to follow the caterpillar without it looking unnatural.

This could perhaps be improved (made more natural) by more loosely coupling the followers from the caterpillar: in other words, always using the "catch up" algorithm even while in formation.  This would make it so that followers could fall behind, get ahead, etc. to some extent.  We could even have followers be affected by obstructions then, too.

So, thoughts?

**Comment by FlyingJester** [comment]
Why wait until the leader has moved? Why not just start the follower walking towards the leader immediately when FollowPerson is called?

**Comment by fatcerberus** [comment]
Because that's not their target position.  The correct formation isn't known until the leader has taken [distance / speed] steps; that's why in almost all RPGs with this function, the chain acts as an actual chain with followers initially placed under the leader.

**Comment by fatcerberus** [comment]
Here's a first prototype of the new FollowPerson algorithm:
https://github.com/fatcerberus/minisphere/commit/fb94ac9439e957f7bd1351b78302ca2b6a6566d2

Try it out and let me know what you think.

It still tracks historical positions (a very handy shortcut to avoid the need for pathfinding), however, followers walk into formation under their own power and continue to do so even once they are in position.  No person ever has his position set directly.  This makes the overall effect look much more natural, particularly with long follower chains.  As a nice bonus, followers are also affected by obstructions now. :smile:

**Comment by fatcerberus** [comment]
So one more question, this time regarding what happens when person with followers is destroyed.  If you have a follow-chain like this: leader<follower<follower<follower<etc. (each person tracks the one in front of him), what should happen if the chain is broken?  In other words, when DestroyPerson() is called on a person in the middle of the chain.

Sphere's behavior is to sever the chain, leaving all persons behind the one removed without a leader.  I'm not entirely happy with that setup, but I also don't want to break compatibility for no reason (games may rely on the chain being severed).  But I was thinking, in case a person in the chain is removed, the person(s) following him could then attach to _his_ leader upon destruction, preserving the chain.  Thoughts?

**Comment by FlyingJester** [comment]
I don't think that's the logical thing to do.
I would expect that many games only expect a certain, very few persons to ever have followers. Simply making the first follower the new leader sounds like something most games would have to undo.

**Comment by fatcerberus** [comment]
Just to make sure we're on the same page (you confused me with the "first follower" thing):

Say we have a chain like this:

`Scott (leader) < Bruce < Lauren < Robert < maggie`

...and now let's say Lauren gets eaten by a bear or something (and we'll further say the bear is named `DestroyPerson` because why not? :o).  Under Sphere we now have two separate chains:
1. `Scott (leader) < Bruce`
2. `Robert (leader) < maggie`

Except that makes maggie useless because she's still following Robert, who no longer has a leader (she got eaten by a bear, remember?).  What I'm proposing is to automatically condense the chain:
`Scott (leader) < Bruce < Robert < maggie`

Do you think that's something most games would want to undo?  Seems intuitive enough to me, but...

**Comment by FlyingJester** [comment]
Oh, I see. I thought that, in your example, Bruce, Lauren, Robert, and Maggie are all following Scott, in that order. I see what you mean now.
But I would think it is really up to the game's logic either way. The game destroyed the person, the game should determine the implications of this. I think the engine should provide the simplest case. That way it's as easy as possible for the game to determine what happens. I think the simplest case really is to just have a dead chain at the end in this situation.

**Comment by fatcerberus** [comment]
The results of this effort have been merged into master in case anyone wants to test it out.

**Comment by fatcerberus** [comment]
So there's a kind-of-not-so-small issue with the new algorithm: because followers move under their own power and thus honor obstructions, they have a tendency to get caught up on corners and such and have difficulty freeing themselves.  I thought my trick of doing diagonal movement in two steps (horizontal then vertical) would ease this, but apparently it's just not enough.

This, combined with the inability to predict the exact path each follower will take, makes FollowPerson difficult to utilitize in cutscenes.

Lithonite would most likely fix this, but that's not built in.  I'm probably just going to have to break down and use some form of A\* search to allow followers get free if they meet too many obstructions in a short time frame.
