### ISSUE TITLE
Updated macOS/Mac OS X compilation instructions

### ISSUE THREAD

**Issue by apollolux** [spheredev/neosphere#248]
Hey there! I'm looking to compile minisphere on Mac once again, but this time I'm on High Sierra (10.13). While I would hope that any Mac compilation instructions would also cover older versions like Mavericks, I seem to have forgotten most of how to compile minisphere from scratch.

Allegro is installed via homebrew (brew install allegro) and is 5.2.x stable. libmng is 2.0.3 compiled manually since it doesn't exist in homebrew yet for some reason and not having it resulted in a "not found" error.

I'm getting the following error using `make`:
<pre>
ld: unknown option: -rpath=$ORIGIN
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [bin/minisphere] Error 1
</pre>

[This StackOverflow question](https://stackoverflow.com/questions/42344932/how-to-include-correctly-wl-rpath-origin-linker-argument-in-a-makefile) shows that there's a comma instead of an equals sign between -rpath and $ORIGIN. Changing that results in the following error:

<pre>
ld: warning: ignoring file dep/lib/x86_64/libChakraCore.so, file was built for unsupported file format ( 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 ) which is not the architecture being linked (x86_64): dep/lib/x86_64/libChakraCore.so
Undefined symbols for architecture x86_64:
( many errors about jsal-db5b21.o )
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [bin/minisphere] Error 1
</pre>

What can we do to resolve this?

**Comment by fatcerberus** [comment]
Paging Dr. @rhuanjl...

**Comment by rhuanjl** [comment]
I gave up trying to tweak the make file and made an XCode project for it - I am planning to share this at some point but it's not really in a shareable state quite yet.

Mostly because I didn't want to be dependent on a homebrew shared lib version of allegro - as I wanted to be able to make a self contained redistributable version of miniSphere. See link: https://github.com/fatcerberus/minisphere/releases/download/v5.0.0/miniSphere-5.0.0-macOS.zip

(I'll update to the latest version soon - waiting untill I can build with some patches in chakracore that haven't been made yet)

The specific error you're hitting now though is that the make file tries to link the linux version of ChakraCore - you need a macOs build of chakracore - specifically for the latest miniSphere you need 1.8 or later (the latest official binary is 1.76 so you have to build your own)
you can use branch 1.8 or 1.9 or master:
https://github.com/microsoft/ChakraCore/
it's very easy to build:
```
cd some_path_here/chakracore
./build.sh --no-icu --lto -j=7
```
OR
```
cd some_path_here/chakracore
./build.sh --embed-icu --lto -j=7 
```
Note on the options:
**--embed-icu** OR **--no-icu** - this enables/disables certain unicode related JS built in features and functions, I've not seen any sphere game use any of them and it ups the binary size by at least 15mb though technically if we're saying Sphere supports the full JS spec it should be enabled - it requires an extra dependency - the "embed-icu" flag tells the build script to downoad and build that dependency and static link it.

**--lto** - this isn't compulsory but heavily optimises chakracore at the cost of a slightly longer build time - noticeable impact only if running a miniSphere game with some very processor intensive Javscript, but hey I <3 optimising even when un-needed.

**-j=7** - this says use 7 threads for the build, can specify any number you like, but I reccomend 4+

**Anyway once you've built chakracore you'll need to revise the make file to find it etc**

**Comment by rhuanjl** [comment]
One other point I thought of I think you'll also find that cell has to be linked against CoreFoundation (it has some ifdef apple code that uses a corefoundation routine)

**Comment by apollolux** [comment]
I understand the desire to not want to be limited by relying on homebrew . That being said, apparently ChakraCore 1.7.6 is in homebrew as the 'chakra' bottle. On the plus side, it indeed looks like building ChakraCore from scratch is as easy as your one-liner. :)

How shall I get past the rpath issue, though, if using = instead of , is the correct method?

**Comment by fatcerberus** [comment]
1.7.6 will not work, there are a couple features and fixes that went into the master since then that miniSphere relies on and they haven’t pushed an official 1.8.0 yet... :(

**Comment by apollolux** [comment]
Just compiled ChakraCore from git. Changed the Makefile to use...
<pre>
# LD_FLAGS=-Wl,-rpath=\$$ORIGIN
LD_FLAGS=

# LIB_CHAK=libChakraCore.so
LIB_CHAK=libChakraCore.dylib
</pre>
...and replaced them accordingly in the compilation rules. Was too lazy to wrap LIB_CHAK around OS checking for now and left LD_FLAGS empty for now until we can come up with a solution for Mac clang not supporting the syntax of that option.

I'm now down to one error:
<pre>
Undefined symbols for architecture x86_64:
  "_main", referenced from:
     implicit entry/start for main executable
     (maybe you meant: __al_mangled_main)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [bin/minisphere] Error 1
</pre>

**Comment by fatcerberus** [comment]
You need to link to allegro_main on macOS, for whatever reason.

**Comment by apollolux** [comment]
Also, a lot of "warning: using the result of an assignment as a condition without parentheses [-Wparentheses]" even though I didn't explicitly declare -Wparentheses ; maybe for some reason it's on by default for me?

**Comment by fatcerberus** [comment]
Yeah, clang seems to want to generate those by default even on Linux.  I should do something about it, but I really don’t like the extra parens. :(

**Comment by apollolux** [comment]
But yea, adding allegro_main to the engine libs indeed allowed it to compile. Is it now just a matter of replacing the binaries in miniSphere.app and adjacent?

**Comment by apollolux** [comment]
Never mind, error due to the rpath removal thing:
<pre>
dyld: Library not loaded: @rpath/libChakraCore.dylib
  Referenced from: /Users/lux/Documents/dev/minisphere/bin/minisphere
  Reason: image not found
Abort trap: 6
</pre>

**Comment by rhuanjl** [comment]
I use the following mini script to fix the search path for ChakraCore:
```
install_name_tool -change @rpath/libChakraCore.dylib @executable_path/../SharedSupport/libChakraCore.dylib ${BUILT_PRODUCTS_DIR}/${EXECUTABLE_PATH}
```
You'll need to change the last part to the path to your executable, in the above example probably:
```
install_name_tool -change @rpath/libChakraCore.dylib @executable_path/../SharedSupport/libChakraCore.dylib /Users/lux/Documents/dev/minisphere/bin/minisphere
```
Not sure if you can put that in the make file or if you'll need to run it separately from the command line.

That assumes that you put the compiled libChakraCore.dylib in a folder called SharedSupport one level down from where you have the executable - you could alternatively specify some other location.

Note if making a macos .app bundle then @executable_path = the location of the unix executable in miniSphere.app/contents/macos not the app bundle itself.

**Comment by apollolux** [comment]
The install_name_tool suggestion with modified paths worked, but now I get a "No system font" error dialog when trying to open a game .sgm file (currently using Sir Boingers 2.1.1 from the GDrive):

"miniSphere was unable to find the system font or an error occurred while loading it.  As a default font is required for normal operation, the engine will now close."

This also happens with the pre-packaged 5.0.0 app.

**Comment by rhuanjl** [comment]
Normally that would mean the system folder was missing but with the zip I've posted the system folder is there, just tested it and it doesn't work for me either, will investigate later don't have any more time now.

Shared a new zip file with you in discord (took my current working copy of miniSphere and zipped it)

If it doesn't work then there's something about uploading it to the internet and downloading it again that breaks it.

**Comment by apollolux** [comment]
Got the zip file and replaced mine. Also ran cell on [fatcerberus/kh2bar](https://github.com/fatcerberus/kh2bar) as suggested on Discord as well and loaded the resulting spk, still get the "no system font" dialog.

FYI, needed to do the install_name_tool thing on cell too if I didn't use the one in the dropboxed app.

**Comment by fatcerberus** [comment]
I wonder if it's a permissions issue with the system folder/app package in general?  It might need to have certain permissions which get lost in the zip-unzip process.

**Comment by fatcerberus** [comment]
@apollolux Based on our discussions on Discord I think you got miniSphere running so I’ll close this issue. :)
