### ISSUE TITLE
Old MOD music doesn't seem to play

### ISSUE THREAD

**Issue by DaVince** [spheredev/neosphere#32]
I tested out the Sully Chronicals (sic) port and the module music isn't playing. It's of the old MOD type. The music plays properly in stock Sphere 1.5.

**Comment by fatcerberus** [comment]
I suspect I may not be able to fix this immediately.  As with the looping, it's probably an Allegro bug.

What's interesting is that the mods are apparently being loaded--if loading fails (`al_load_audio_stream` returns NULL) you will get a "Failed to load" exception.  The game runs normally otherwise, so I won't rule out a minisphere bug entirely. :-)

**Comment by fatcerberus** [comment]
So it turns out the MOD music plays just fine.  A trip through the debugger revealed that `LoadSound()` wasn't being called at all.  "Odd", I thought.  A few unfruitful searches of the source later for LoadSound calls, yours truly figures out the cause: The BGM is defined in the map file, and minisphere doesn't support that because, you know, Bruce never actually bothered to implement it. :stuck_out_tongue_closed_eyes:

Well, it's implemented now.  minisphere 1.2.2 is available on the forums. :smile:
