### ISSUE TITLE
GetKey() is not aware of Ctrl, Shift or Alt

### ISSUE THREAD

**Issue by DaVince** [spheredev/neosphere#33]
I decided to try to get my ancient game Pokémon GS/SS running with minisphere. I managed to get it to enter the main menu, upon which I noticed something: I cannot select any options.

The thing is, this game uses the Ctrl key for menu selection, and the menu is coded in a way that it relies on `GetKey()` (Hey, give me a break, I was a shitty coder back then. :stuck_out_tongue:).

After writing a little test case, it appears that minisphere does not detect Ctrl, Shift and Alt keypresses at all, while the original Sphere did. This is what caused it to break.

**Comment by fatcerberus** [comment]
Ah.  See, when I implemented `GetKey()` I assumed it only tracked "typing" keys (in minisphere it's implemented by watching for KEY_CHAR events--this gives me key-repeat support without extra effort).  Apparently Sphere decided to be an odd duck and queues ALL keys, even modifiers.  It's a pain to fix because now that means I have to handle key-repeat myself.

The thing is, I'm not even sure I _want_ to fix it.  I'm almost inclined to consider Sphere's behavior a bug because normally modifier keys don't go into a key queue--they are always immediate.  Nonetheless, it is a compatibility issue.

Could you do something for me?  Write a loop that just calls GetKey() continuously and prints the keycode, and tell me if Sphere auto-repeats the modifiers.  I know it does for at least alphanumeric keys, but...

**Comment by DaVince** [comment]
From memory, it does the "pause a second, then repeat the keys" thing, but I'll double check for you.

**Comment by DaVince** [comment]
Okay, I tested, and Sphere is weird:

When holding a non-modifier key (space, A, etc) it waits a second and then repeats.
When holding ctrl, alt or shift, it prints the keycode once, but doesn't repeat at all.
When holding a letter and then proceeding to hold a modifier key, it'll print the modifier key once and then continue repeating the letter code.

I guess it does go into the queue, but only immediately and only once.

So if you just make it so modifier keys are read and leave the key-repeat up to the system, it'll work just like 1.5. It looks like they took the easy way out too.

Code I tested with is this:

```
function game() {
  var font = GetSystemFont();
  var text = "";
  FlipScreen();

  while(true) {
    text += GetKey() + " ";
    font.drawTextBox(10,10,300,220,0,text);
    FlipScreen();
  }
}
```

As for why implementing this: it's not uncommon for games to use these modifier keys. DOS games used it all the time, and I use it in a few different games. (Though I believe I have dropped usage of `GetKey()` a lot more). minisphere being able to detect them would be appreciated.

**Comment by fatcerberus** [comment]
Okay, the crux of the issue appears to be that Win32 WM_KEYDOWN repeats keys (except modifiers), while Allegro's equivalent KEY_DOWN does not (it only fires when you first press the key).  KEY_CHAR does repeat, but doesn't recognize modifiers.

I should be able to fix it by checking for Ctrl/Alt/Shift in KEY_DOWN and putting them into the queue manually.  This would match Sphere's behavior I think.

**Comment by fatcerberus** [comment]
Okay, latest commit should contain the fix.

**Comment by DaVince** [comment]
Awesome, thanks so much for the fix. Works perfectly.
