### ISSUE TITLE
Persons on hidden layer are also hidden when they shouldn't be

### ISSUE THREAD

**Issue by DaVince** [spheredev/neosphere#37]
In Sphere 1.5, you can hide a layer and the people that are on this same layer will still be visible. In minisphere, they are hidden.

However, this clashes with a mapping technique that I have been using in Pokemon GS/SS: using a single special tile for obstructions and then hiding this layer. This makes mapping easier and obstruction issues visible.

Sphere 1.5, with the obstruction layer shown and hidden:
![screenshot 2015 06 08 22 15 23 0313](https://cloud.githubusercontent.com/assets/105533/8044339/43672dfc-0e2c-11e5-852e-946bee8ed1c6.png)
![screenshot 2015 06 08 22 16 21 0178](https://cloud.githubusercontent.com/assets/105533/8044340/43681d48-0e2c-11e5-920c-234250baa3f2.png)

minisphere, with the obstruction layer shown and hidden:
![snapshot-1433794556](https://cloud.githubusercontent.com/assets/105533/8044351/54e7b7cc-0e2c-11e5-8d21-d945305c3df8.png)
![snapshot-1433794598](https://cloud.githubusercontent.com/assets/105533/8044352/54e95d52-0e2c-11e5-9b52-0e25cba42453.png)

**Comment by fatcerberus** [comment]
That's interesting, and very counterintuitive.  It'll require a few changes to the layer rendering code to emulate, but shouldn't be too bad.

Currently if a layer is hidden it is skipped wholesale by the renderer.  That seemed the most obvious solution, and it seemed to match sphere's, but it looks like I missed something.  Which is odd, since I paid particular attention to the rendering code when reviewing it...

I'll add it to my list of bugs to fix. :-)

**Comment by fatcerberus** [comment]
So it turns out I did misread the Sphere 1.6 source after all.  It only skips rendering tiles for a hidden layer, entities are unaffected.  Which of course I didn't need proof for as you posted screenshots, but my OCD means I always have to double-check. :sweat_smile: 

A fix for this has been pushed to master, 8b33c6109cf894720630dd70c46e96d3b6d72a45.  Try it out and let me know!

**Comment by DaVince** [comment]
Works now, nice work as usual! :space_invader:
