### ISSUE TITLE
Lithonite tech demo is buggy

### ISSUE THREAD

**Issue by DaVince** [spheredev/neosphere#39]
The Lithonite tech demo that comes with the 1.3.0 release does not seem to be working properly on Linux:
- Many triggers, like the cliff drop, the conveyor belt and the little arrows seem to be ignored.
- When pushing against the NPC, the water layer disappears completely and is replaced with black.
- The game seems to be running at "60/114 fps" for me.
- Talking to the NPC seems bugged

I believe the ice is broken too, but I don't remember exactly what happens to the little ice section in the original.

**Comment by fatcerberus** [comment]
Regarding the FPS, that demo for whatever reason is set to run at 120fps, it looks like the frameskip algo is just doing its job. :). 60/114 means 60 frames rendered, 114 updated -- it got to near full speed by dropping half of the frames.

The water layer disappearing is intentional, Sphere does the same thing.  The only difference is that Sphere doesn't clear the backbuffer when rendering maps, so you get a neat mirror-blur effect.  It's technically exploiting a bug though.

The triggers and zones not working is likely a legitimate regression.  I'll have to look into it, I may have broken something when I added 4-player support.

I don't know about the talking though... What happens if you run the same game in 1.5?

**Comment by DaVince** [comment]
Okay, fair enough. Regarding the talking:
When pressing ctrl in 1.5 near the Celes at the bottom, there will be a text box over the map about the water turning red. In minisphere, it usually won't display anything, and when it does, it's only the text box on a black screen and not the map.

**Comment by DaVince** [comment]
Also, what does F5 normally do in minisphere? It restarts the game when I press it.

**Comment by fatcerberus** [comment]
For what it's worth, I have a feeling the dropped frames may be due to vsync - hence the flat 60.  The engine is then struggling to keep up because the game wants 120.  The fact that it managed to get it up to 114 in that circumstance is actually pretty impressive.

**Comment by fatcerberus** [comment]
Press F1 in that demo.  I think the game itself binds it as a restart key.  minisphere only intercepts F10, F11 and F12 with the same meanings as 1.5 (full screen, FPS count, screenshot)

**Comment by DaVince** [comment]
Huh. You're right. I even made sure to test in Sphere 1.5, and F5 did nothing there... Wait, now it does. Okay, sorry about that.

As for the 114 FPS, what's the bottleneck? It doesn't seem to be using 100% of a single core... Performance is still nice, so I'm not really complaining, but I'm just wondering why it can't get to 120 FPS.

**Comment by fatcerberus** [comment]
In assuming floating point error.  The engine doesn't expect the vsync paused and them struggles to make up the difference.  Especially since it's trying to conserve CPU at the same time.  That's my theory anyway.

**Comment by fatcerberus** [comment]
I almost wonder if that text box bug you mention is some weird render-order glitch that only happens under specific circumstances.  I've noticed in Sully Chronicals during cutscenes, sometimes it doesn't clear the text box properly and draws the next text over the old.  This could be a manifestation of the same bug which causes that, not sure.

Nothing I can do at the moment, unfortunately.  I won't be near a computer for another 4 hours at least.

Also, there were SO MANY typos in my last post, I suspect a bunch of them are due to the braindead autocorrect feature on my phone though...

**Comment by fatcerberus** [comment]
Okay, now that I'm home I got a good look at this.
- The zones and triggers seem to work fine on my end.  The conveyor moves me along automatically, the ice is slippery (think SMB3 World 6) and the cliff drop works.  Even the little patch of arrows that change your movement direction.  You're sure you're testing with 1.3.0, right? :sweat_smile: 
- The water layer disappearing is by design and, as previously mentioned, exploits a bug in Sphere (backbuffer not cleared between map frames) which is fixed in minisphere.  Other than this neat little exploit, not clearing the backbuffer is generally undesirable behavior, so "fixing" this is inadvisable.
- minisphere apparently doesn't like vsync.  Moving on... :stuck_out_tongue_winking_eye: 
- The talking bug I'm not sure about.  This is the function the game calls when you talk to her:

``` javascript
function Dosign(msg)
{
    var fnt=GetSystemFont();
    var wdw=GetSystemWindowStyle();
    wdw.drawWindow(32, 150, 248, 64)
    fnt.drawTextBox(32, 144, 248, 80, 0, msg+"\n\t\t\t\t\t\t\tPress key");
    FlipScreen();
    while(IsKeyPressed(Keys.talk)){ }
    while (!IsAnyKeyPressed()){}
}
```

Note that it renders the window and text and then FlipScreens, then waits for a key.  So obviously at the point the talk script is called, the backbuffer is empty.  Which makes sense--internally, minisphere calls `update_map_engine()` before `render_map()`.

Interestingly enough, Sphere appears to do it in the reverse order--render first, then update, then process input.  Doing that would fix this bug.  However, the last time I did map processing in that order it caused weird intra-frame race conditions...

I'll see what I can do anyway.

**Comment by fatcerberus** [comment]
Hm, I was wrong about the talking.  Sphere's MapEngine() loop essentially does this, in pseudocode:

```
while(true) {
    RenderMap();
    FlipScreen();
    UpdateMapEngine();
    ProcessMapInput();  // fictitious
}
```

So this is another bug caused by minisphere doing the right thing and clearing the backbuffer after a FlipScreen.  Oh well.

So that means the only actual issue here is the failure to fire the zone scripts.  Not sure what's going on there, I'll have to investigate some more.

**Comment by fatcerberus** [comment]
As of the 3 latest commits, most of these issues should be fixed.

For those curious, because I always like to explain bugs--for posterity if nothing else: :sweat_smile: 
- The talk scripts not firing was caused by a discrepancy between Sphere and minisphere's handling of talk activation.  Sphere will allow a talk activation even if the input person has commands in their queue, while minisphere did not.
- The flaky zones were due to me not initializing `zone.steps_left` on map load, causing it to be initialized with some garbage value.  It that number ends up being negative, it automatically fires the zone script and resets the counter, and everything works normally.  If it's some huge positive value, though...
- The icy patch was indeed broken.  It worked in 1.2.4, but in 1.3 it was busted.  Turns out this conditional, likely written in haste during implementation of 4-player support, was the cause:<br>

``` c
if (person != NULL && person) {
```

This is the condition which checks whether it's okay to accept player input or not.  The part after the `&&` should be `!is_person_busy(person)`.  Whoops!

So yeah, try the latest master and let me know if it's fixed.  I'm crossing my fingers for no stupid compile errors this time...

**Comment by DaVince** [comment]
Works, works and works! :+1:

**Comment by fatcerberus** [comment]
Oh good, time for 1.3.1 then it looks like. :smile:
